# SOURCE: PSK
# URL: https://github.com/PolymerElements/polymer-starter-kit/blob/master/.travis.yml
# TESTED: No

language: node_js
sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - '7'
  - '6'
  - '5'
  - '4'
before_script:
  - npm install -g bower polymer-cli
  - bower install
script:
  - xvfb-run polymer test





# SOURCE: Collaborne
# URL: https://medium.com/collaborne-engineering/how-to-build-polymer-components-with-github-and-travis-67683ef8bf0d#.4qpzxl1vj
# TESTED: No

language: node_js
sudo: false
node_js:
- stable
addons:
  firefox: '42.0'
cache:
  directories:
  - node_modules
before_script:
- npm install web-component-tester bower polylint
- bower install
- bower install -s https://${GH_TOKEN}@github.com/Collaborne/collaborne-build-tools.git
- polylint
- export PATH=$PWD/node_modules/.bin:$PATH
script:
- xvfb-run wct
after_success: '[ ${TRAVIS_PULL_REQUEST} = "false" ] && [ ${TRAVIS_BRANCH} = "master" ] && bower_components/collaborne-build-tools/gpages_build.sh Collaborne info@collaborne.com'
env:
  secure: k1v4LU5whn4jo8wAnkW4ZcNSv4lF0xiKF/QUARwHC2kCOR8DJBA+6YlI+WI/Z2cCiJZbAAIHCdftWJ2f9Zb9ecJ6q+oSFFGIGafwWWtfjCHLzpPblgd2b946DrmTGnfczJWPvv2gAMuJfQhJAeWgHUpFo3SXRC2dBznmqgBuhJJqIlqmNwSiYAeiFi7KmaOuRinw9DJkFzgQDAS44y0cARliyHVviAGBUaqMLkXyF9KbCRa8rbNIWVLZeWXDPSpxb7POtyx8jg3HPVD35ZQENEyhIvKmQDK3UiS/X8Nf+qh5zuTVm4dB3R4gcnZNLRcTrqruVEchuWO8qLPVLx0v7DPpPiwNNDixczRtV9nqolWjBSDT3klAXhR55NOQruQ0WvkkY2aVTgzjmXzgqLv5yW+k2WhMfUZ1p7gJBm6CKztBYzs5E1i5+AdWsAEVZRcsb0cjy3kvB8/UwbGKpggqjQ1C2dU+SecPd7Qbld1Eh/R3o83Vw0cbcOOsG4AlONSo29RKh8aPeL05YuX1yPNsi/+3jvWEC3mRN/mE1kWZwzyJVofsX5/uTC4EY7YCQZyVL5CaI6fIawb7BRZshvsPw/JH3u1foB1zKzpcDK8odw3fV1CvIzRsNA0EO2a/VfrY0Jy9guxH7zJZn9BzkesHIQxLaqS+2VnGBilrCn09Va4=







# SOURCE: Collaborne NEW***
# URL: https://github.com/Collaborne/paper-contact
# TESTED: No

dist: trusty
sudo: false
group: beta

language: node_js
node_js:
- node

addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

cache:
  directories:
  - node_modules
  - "$HOME/.cache/bower"

before_install:
- "if [ -d node_modules ] && [ x$(cat node_modules/.last-node-version 2>/dev/null) != x$(node -e 'console.log(process.version)') ]; then npm rebuild && node -e 'console.log(process.version)' > node_modules/.last-node-version; fi"

before_script:
- npm install web-component-tester bower polylint
- bower install
- polylint --no-recursion
- export PATH=$PWD/node_modules/.bin:$PATH

script:
- xvfb-run wct

after_success: '[ ${TRAVIS_PULL_REQUEST} = "false" ] && [ ${TRAVIS_BRANCH} = "master" ] && bower install -s https://${GH_TOKEN}@github.com/Collaborne/collaborne-build-tools.git && bower_components/collaborne-build-tools/gpages_build.sh Collaborne info@collaborne.com'

env:
  secure: BcLCo20s5hcfinR5cslFVTGv2rWyGtuYdAZIoNZdgoT8/E7PxMmoP9wmlDYJPF3hjff5QaXlQPVWMhXfh4kwcBPKOlmBgpQ/NugCwLJGH9XuDyEYVHfBzv5Sy7BX7V94pOBzwBT0UzND5MAZjx9yw2pEv/KjTC6l56DcYewtbw+6K/6XX1NSg9FPqDw9ArFS7jT25mt7QJEIE+Ii4tEyqdkpMiNlF4oyeUaoY5NVdtvchz6fldfDwV4VETXVb7YxHv4+C80Drp2L+iaYyHNkVa5CU90E6YNM/XNQJwkcyMDyJ2ym3pBs5LlC9UE+SHJdolTNEHhJbhR9lDP831NMydQEQqhrNqPrKp4YE29uhIXTag4UXdEQOC6gY74Isf6F8R3zuA3jlElb4M7t5xt+rjjbXsxYQ22mMXJzta06bOxgVHtUnrhppRrGMNBJLyAG6Rm8A6kEWWK/mszAqZYjrPebeBTX7Wx/YB5j0Jx4iYvpkvFgJcSP08AKVwEhoIumwAtgoaV8i1FL7JLxl8zDqXnhSQiMbh/8UC0i0+fRp0JA4OgPBBrEnB2ae5w3vO31yINer3LrGbfhl2ViYKi8d6T45Yj3TNHYqu8VYxnpSpAuJ44g+GzYA2IPa3Xz0442rmozmyjmtcAFz7jZ3aQfD+C825SS4uhM7htNF7dUVeE=










# SOURCE: Polymer Tools
# URL: https://github.com/Polymer/tools/tree/master/travis 
# TESTED: No

language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- polylint
script: xvfb-run wct



# SOURCE: Zisis Maras
# URL: https://zisismaras.me/polymer/2015/12/02/automatic-github-pages-for-polymer-elements-with-travis-ci.html
# TESTED: No

language: node_js
node_js: stable
script:
  - bash ./gpages_build.sh <github-username> <repo-name> <git-name> <git-e_mail>
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH




after_success: 

'[ ${TRAVIS_PULL_REQUEST} = "false" ] && 
 [ ${TRAVIS_BRANCH} = "master" ] && 
 
 bower install -s https://${GH_TOKEN}@github.com/Collaborne/collaborne-build-tools.git && 
 bower_components/collaborne-build-tools/gpages_build.sh Collaborne info@collaborne.com'

  - bash ./gpages_build.sh <github-username> <repo-name> <git-name> <git-e_mail>